/**
 * 模块名称：config.ts
 * 配置工具模块
 *
 * 功能描述：
 * - 提供配置文件读写功能
 * - 管理环境变量和配置文件
 * - 验证和规范化 Affine 服务器 URL
 * - 加载完整配置并提供默认工作区 ID
 *
 * 配置加载优先级：环境变量 > 本地 .env > 全局 ~/.affine-cli/affine-cli.env
 *
 * 导出的配置项：
 * - AFFINE_BASE_URL: Affine 服务器地址（默认 https://app.affine.pro）
 * - AFFINE_API_TOKEN: 认证凭据
 * - AFFINE_WORKSPACE_ID: 默认工作区 ID
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

/**
 * GLOBAL_CONFIG_DIR: 全局配置文件目录
 * 路径：~/.affine-cli/
 */
export const GLOBAL_CONFIG_DIR = path.join(os.homedir(), '.affine-cli');

/**
 * GLOBAL_CONFIG_FILE: 全局配置文件路径
 * 路径：~/.affine-cli/affine-cli.env
 */
export const GLOBAL_CONFIG_FILE = path.join(GLOBAL_CONFIG_DIR, 'affine-cli.env');

/**
 * LOCAL_CONFIG_FILE: 本地配置文件路径
 * 路径：<当前工作目录>/.env
 */
export const LOCAL_CONFIG_FILE = path.join(process.cwd(), '.env');

/**
 * readKeyValueFile: 读取 key=value 格式的配置文件
 *
 * @param filePath - 配置文件路径
 * @returns 配置键值对对象，文件不存在时返回空对象
 *
 * 注意事项：
 * - 跳过空行和以 # 开头的注释行
 * - 使用 = 作为键值分隔符
 */
export function readKeyValueFile(filePath: string): Record<string, string> {
	if (!fs.existsSync(filePath)) return {};
	const content = fs.readFileSync(filePath, 'utf-8');
	const result: Record<string, string> = {};
	for (const line of content.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const eq = trimmed.indexOf('=');
		if (eq === -1) continue;
		result[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
	}
	return result;
}

/**
 * loadConfigFile: 加载配置文件的合并结果
 *
 * @returns 合并后的配置键值对对象
 *
 * 配置优先级（从高到低）：
 * - 环境变量（process.env）
 * - 本地 .env（LOCAL_CONFIG_FILE）
 * - 全局配置文件（GLOBAL_CONFIG_FILE）
 */
export function loadConfigFile(): Record<string, string> {
	const globalConfig = readKeyValueFile(GLOBAL_CONFIG_FILE);
	const localConfig = readKeyValueFile(LOCAL_CONFIG_FILE);
	const merged: Record<string, string> = { ...globalConfig };
	for (const [key, value] of Object.entries(localConfig)) {
		if (value) merged[key] = value;
	}
	return merged;
}

/**
 * writeConfigFile: 写入配置文件
 *
 * @param vars - 配置键值对
 * @param useLocal - 是否写入本地配置文件，默认 false 写入全局配置
 *
 * 注意事项：
 * - 全局配置写入使用原子操作（先写临时文件再重命名）
 * - 本地配置直接写入当前目录的 .env 文件
 */
export function writeConfigFile(vars: Record<string, string>, useLocal: boolean = false) {
	const configDir = useLocal ? process.cwd() : GLOBAL_CONFIG_DIR;
	const configFile = useLocal ? LOCAL_CONFIG_FILE : GLOBAL_CONFIG_FILE;

	const lines = [
		'# Affine CLI credentials',
		'# Generated by: affine-cli login',
		`# ${new Date().toISOString()}`
	];
	for (const [key, value] of Object.entries(vars)) {
		if (value) lines.push(`${key}=${value}`);
	}
	lines.push('');

	if (useLocal) {
		fs.writeFileSync(configFile, lines.join('\n'));
		return;
	}

	const tmpFile = path.join(configDir, `.config.tmp.${process.pid}`);
	try {
		fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
		fs.writeFileSync(tmpFile, lines.join('\n'), { mode: 0o600 });
		fs.renameSync(tmpFile, GLOBAL_CONFIG_FILE);
	} catch (err) {
		try {
			fs.unlinkSync(tmpFile);
		} catch {}
		throw err;
	}
}

/**
 * validateBaseUrl: 验证并规范化 URL
 *
 * @param input - 输入的 URL 字符串
 * @returns 规范化后的 URL（去除尾部斜杠）
 * @throws 如果 URL 无效或协议不支持
 *
 * 注意事项：
 * - 不支持嵌入式凭据（user:pass@host）
 * - 仅支持 http/https 协议
 * - 非本地 HTTP URL 会输出警告
 */
export function validateBaseUrl(input: string): string {
	let parsed: URL;
	try {
		parsed = new URL(input);
	} catch {
		throw new Error(`无效的 URL: ${input}`);
	}
	if (parsed.username || parsed.password) {
		throw new Error('URL 不能包含嵌入式凭据 (user:pass@host)');
	}
	if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
		throw new Error(`不支持的 URL 协议: ${parsed.protocol} (仅支持 http/https)`);
	}
	const host = parsed.hostname;
	const isLocal =
		host === 'localhost' || host === '127.0.0.1' || host === '::1' || host === '0.0.0.0';
	if (parsed.protocol === 'http:' && !isLocal) {
		console.error('警告: 使用非本地 HTTP URL，建议使用 HTTPS');
	}
	return parsed.origin + parsed.pathname.replace(/\/$/, '');
}

/**
 * env: 获取生效的配置值
 *
 * @param name - 环境变量名
 * @param file - 配置文件对象
 * @param fallback - 备用值
 * @returns 配置值
 *
 * 优先级（从高到低）：环境变量 > 配置文件 > 备用值
 */
function env(name: string, file: Record<string, string>, fallback?: string): string | undefined {
	return process.env[name] || file[name] || fallback;
}

/**
 * loadConfig: 加载完整配置
 *
 * @returns 配置对象，包含 baseUrl、apiToken、cookie、defaultWorkspaceId
 *
 * 注意事项：
 * - AFFINE_BASE_URL 默认值为 https://app.affine.pro
 * - 其他配置项无默认值，从环境变量或配置文件读取
 */
export function loadConfig() {
	const file = loadConfigFile();
	const baseUrl = validateBaseUrl(env('AFFINE_BASE_URL', file, 'https://app.affine.pro')!);
	const apiToken = env('AFFINE_API_TOKEN', file);
	const defaultWorkspaceId = env('AFFINE_WORKSPACE_ID', file);

	return {
		baseUrl,
		apiToken,
		defaultWorkspaceId
	};
}

/**
 * redactSecret: 脱敏显示密钥
 *
 * @param value - 原始密钥
 * @returns 脱敏后的值
 *
 * 使用示例：
 * - "abc123" → "****3"
 * - "longer-secret-key" → "abcd…ey"
 */
export function redactSecret(value: string | undefined): string | null {
	if (!value) return null;
	if (value.length <= 8) return '*'.repeat(value.length);
	return `${value.slice(0, 4)}…${value.slice(-4)}`;
}

/**
 * getWorkspaceId: 获取工作区 ID
 *
 * @param paramsWorkspaceId - 可选的工作区 ID 参数
 * @returns 工作区 ID
 * @throws 如果未指定工作区 ID 且配置中也没有设置
 *
 * 优先级（从高到低）：
 * - 参数 paramsWorkspaceId
 * - 配置中的 AFFINE_WORKSPACE_ID
 *
 * 使用示例：
 * - getWorkspaceId() // 使用配置中的默认工作区
 * - getWorkspaceId('workspace-123') // 使用参数指定的工作区
 */
/**
 * 获取 Affine 基础 URL
 *
 * @returns 基础 URL（默认 https://app.affine.pro）
 */
export function getBaseUrl(): string {
	const config = loadConfig();
	return config.baseUrl;
}

/**
 * 获取工作区 ID
 *
 * 优先级：参数 > 环境变量/配置文件 > 报错
 *
 * @param paramsWorkspaceId - 可选的 workspace ID 参数
 * @returns 工作区 ID
 * @throws 如果没有配置 workspaceId
 */
export function getWorkspaceId(paramsWorkspaceId?: string): string {
	const config = loadConfig();
	const workspaceId = paramsWorkspaceId || config.defaultWorkspaceId;
	if (!workspaceId) {
		throw new Error(
			'未指定工作区 ID，请使用 --workspace 参数或在配置中设置 AFFINE_WORKSPACE_ID'
		);
	}
	return workspaceId;
}
